# Generated by Django 4.1.13 on 2025-06-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productattachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattachment",
            name="handle",
        ),
    ]
