# Generated by Django 4.1.13 on 2025-06-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_productattachment_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattachment",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
