# Generated by Django 4.1.13 on 2025-06-22 09:52

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_stripe_price_id_product_stripe_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattachment",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/dimaburdenuk/python/django-micro-ecommerce/local-cdn/protected"
                ),
                upload_to=products.models.handle_product_attachment_upload,
            ),
        ),
    ]
