# Generated by Django 4.1.13 on 2025-06-22 18:01

from django.db import migrations, models
import micro_ecom.storages.backends
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_productattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattachment",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=micro_ecom.storages.backends.ProtectedFileStorage(),
                upload_to=products.models.handle_product_attachment_upload,
            ),
        ),
    ]
